version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.builtBy=goreleaser

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}_{{ .Timestamp }}"

brews:
  - name: "gignr"
    homepage: "https://github.com/jasonuc/gignr"
    license: MIT
    description: A CLI to effortlessly manage and generate .gitignore files
    directory: Formula
    repository:
      owner: jasonuc
      name: homebrew-tap
      branch: main

release:
  prerelease: auto
  github:
    owner: jasonuc
    name: gignr
  footer: |
    ## How to Update
    ### Homebrew
    ```
      brew upgrade gignr
    ```

    ### Go
    ```
      go install github.com/jasonuc/gignr@v{{ .Version }}
    ```

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Preformance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - typos
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj